# 站点配置
title: My Jekyll Blog
email: your-email@example.com
description: >- # 这意味着忽略换行符直到下一个配置项
  A simple blog built with Jekyll to share thoughts on web development, design, and more.
baseurl: "" # 子路径，例如"/blog"
url: "" # 基础主机和协议，例如"https://example.com"
twitter_username: jekyllrb
github_username:  jekyll

# 构建设置
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# 分页设置
paginate: 5
paginate_path: "/blog/page:num/"

# 永久链接格式
permalink: /:year/:month/:day/:title/

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
